# NOTE: Generated By HttpRunner v3.1.6
# FROM: basic2.yml


from httprunner import (
    HttpRunner,
    Config,
    Step,
    RunRequest,
    DBDeal,
    DBValidate,
)


class TestCaseBasic2(HttpRunner):
    config = (
        Config("basic test with httpbin")
            .variables(
            **{
                "address": "hefei",
                "mockurl": "${get_mock_url()}",
                "sql": "select * from table where name = 'bob'",
                "mysql_env": "${ENV(mysql_host)}",
                "connect_timeout": 20,
            }
        )
            .base_url("${get_mock_url()}")
            .verify(True)
            .export(*["name"])
            .locust_weight(1)
            .mysql(
            **{
                "host": "172.31.114.19",
                "port": 3306,
                "user": "root",
                "password": "root",
                "database": "blog",
            }
        )
    )

    teststeps = [
        Step(
            DBDeal()
                .mysql(
                **{
                    "host": "172.31.114.19",
                    "port": 3306,
                    "user": "root",
                    "password": "root",
                    "database": "blog",
                }
            )
                .with_variables(
                **{"name": "name", "state": 1, "create": "${get_loginid(created_by)}"}
            )
                .exec(
                """INSERT INTO `blog_tag` (`name`, `created_on`, `created_by`, `modified_on`, `modified_by`, `deleted_on`, `state`) VALUES ( 'Golang2', '1639404686', 'iflytek2', '0', '', '0', '1');""",
                "tags",
            )
                .extract()
                .with_jmespath("tags.list1[0].name", "tag_name"),
            DBDeal()
                .mysql()
                .exec(
                """UPDATE `blog`.`blog_tag` SET `id`="70", `name`="PHP", `created_on`="1639404686", `created_by`="iflytek2", `modified_on`="0", `modified_by`="", `deleted_on`="0", `state`="1" WHERE (`id`="70");""",
                "",
            ),
            RunRequest("headers")
                .get("/v1/tags")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", "000000"),
            DBValidate()
                .mysql(
                **{
                    "host": "172.31.114.19",
                    "port": 3306,
                    "user": "root",
                    "password": "root",
                    "database": "blog",
                }
            ).with_variables(
                **{"name": "name", "state": "state", "create": "${get_loginid(created_by)}"}
            )
                .exec(
                """(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)""",
                "tags",
            )
                .extract()
                .with_jmespath("tags.list1[0].name", "tag_name")
                .validate()
                .assert_equal("tag_name", "cc222"),
            DBValidate()
                .mysql().with_variables(
                **{"name": "name", "state": "state", "create": "${get_loginid(created_by)}"}
            )
                .exec(
                """(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)""",
                "tags",
            )
                .extract()
                .with_jmespath("tags.list1[0].name", "tag_name")
                .validate()
                .assert_equal("tag_name", "cc222"),
        ),
    ]


if __name__ == "__main__":
    TestCaseBasic2().test_start()
