# NOTE: Generated By HttpRunner v3.1.6
# FROM: basic.yml


from httprunner import (
    HttpRunner,
    Config,
    Step,
    RunRequest,
    RunTestCase,
    DBDeal,
    DBValidate,
)


class TestCaseBasic(HttpRunner):

    config = (
        Config("basic test with httpbin")
        .variables(**{"name": "bob"})
        .base_url("https://httpbin.org/")
        .verify(True)
        .export(*["name"])
        .locust_weight(1)
        .mysql(
            **{
                "host": "172.31.114.19",
                "port": 3306,
                "user": "root",
                "password": "rootpass",
                "database": "blog",
                "timeout": 10,
                "isautocommit": True,
            }
        )
    )

    teststeps = [
        Step(
            DBDeal()
            .mysql(
                **{
                    "host": "172.31.114.19",
                    "port": 3306,
                    "user": "root",
                    "password": "rootpass",
                    "database": "blog",
                    "timeout": 10,
                    "isautocommit": True,
                }
            )
            .with_variables(**{"foo1": "$username"})
            .exec(
                "select",
                "(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)",
                "tags",
            )
            .extract()
            .with_jmespath("tags.list1[0].name", "tag_name"),
            DBDeal()
            .mysql()
            .with_variables(**{"foo1": "$username"})
            .exec(
                "select",
                "(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)",
                "tags",
            )
            .extract()
            .with_jmespath("tags.list1[0].name", "tag_name"),
            RunRequest("headers")
            .get("/headers")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.headers.Host", "httpbin.org"),
            DBValidate()
            .mysql(
                **{
                    "host": "172.31.114.19",
                    "port": 3306,
                    "user": "root",
                    "password": "rootpass",
                    "database": "blog",
                    "timeout": 10,
                    "isautocommit": True,
                }
            )
            .with_variables(**{"foo1": "$username"})
            .exec(
                "select",
                "(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)",
                "tags",
            )
            .extract()
            .with_jmespath("tags.list1[0].name", "tag_name")
            .validate()
            .assert_equal("tag_name", "cczhao2"),
            DBValidate()
            .mysql()
            .with_variables(**{"foo1": "$username"})
            .exec(
                "select",
                "(select {},{},{} from blog_tag;).format($name, ${get_loginid(state)}, $create)",
                "tags",
            )
            .extract()
            .with_jmespath("tags.list1[0].name", "tag_name")
            .validate()
            .assert_equal("tag_name", "cczhao2"),
        ),
    ]


if __name__ == "__main__":
    TestCaseBasic().test_start()
